name: Bug Report
description: Report a problem with the plugin
labels: [ Bug-Unconfirmed ]
body:
  - type: textarea
    attributes:
      label: Description of the bug
      description: "What happened?"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce the problem
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: "What should've happened?"
    validations:
      required: true

  - type: input
    attributes:
      label: Debug link
      description: "Run the command `/ecl debug` in-game and provide the link it returns"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional info, if any
      description: Optional
    validations:
      required: false
