name: Bug Report
description: Report a problem with the plugin
labels: Bug-Unconfirmed
body:
  - type: textarea
    attributes:
      label: Description of the bug
      description: "What happened?"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce the problem
    validations:
      required: true

  - type: input
    attributes:
      label: Expected behavior
      description: "What should've happened?"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Output of `/version`
      description: "Upload a screenshot or copy the text from the message"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Output of `/version EntityClearer`
      description: "Upload a screenshot or copy the text from the message"
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Debug file
      description: "Copy and paste the contents of your debug file located in the `/plugins/EntityClearer/` directory after running the `/ecl debug` command"
      render: yaml
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional info
      description: Optional
    validations:
      required: false
